/* Generated from src/medsegagent/label_names.json. Do not edit by hand.
 * Update the JSON, then run: python ops/generate_label_names.py
 * Display names only: upstream label identifiers, masks and files are unchanged.
 */
(() => {
  "use strict";

  const names = new Map(Object.entries({
    "abdominal_cavity": {"zh": "腹腔", "en": "Abdominal cavity"},
    "adrenal_gland_left": {"zh": "左肾上腺", "en": "Left adrenal gland"},
    "adrenal_gland_right": {"zh": "右肾上腺", "en": "Right adrenal gland"},
    "anterior_scalene_left": {"zh": "左前斜角肌", "en": "Left anterior scalene"},
    "anterior_scalene_right": {"zh": "右前斜角肌", "en": "Right anterior scalene"},
    "aorta": {"zh": "主动脉", "en": "Aorta"},
    "atrial_appendage_left": {"zh": "左心耳", "en": "Left atrial appendage"},
    "auditory_canal_left": {"zh": "左耳道", "en": "Left auditory canal"},
    "auditory_canal_right": {"zh": "右耳道", "en": "Right auditory canal"},
    "autochthon_left": {"zh": "左背固有肌", "en": "Left intrinsic back muscles"},
    "autochthon_right": {"zh": "右背固有肌", "en": "Right intrinsic back muscles"},
    "body_extremities": {"zh": "四肢", "en": "Extremities"},
    "body_trunc": {"zh": "躯干", "en": "Trunk"},
    "brachiocephalic_trunk": {"zh": "头臂干", "en": "Brachiocephalic trunk"},
    "brachiocephalic_vein_left": {"zh": "左头臂静脉", "en": "Left brachiocephalic vein"},
    "brachiocephalic_vein_right": {"zh": "右头臂静脉", "en": "Right brachiocephalic vein"},
    "brain": {"zh": "脑", "en": "Brain"},
    "brain_aneurysm": {"zh": "脑动脉瘤", "en": "Brain aneurysm"},
    "breast": {"zh": "乳房", "en": "Breast"},
    "bridge": {"zh": "牙桥", "en": "Dental bridge"},
    "clavicula_left": {"zh": "左锁骨", "en": "Left clavicle"},
    "clavicula_right": {"zh": "右锁骨", "en": "Right clavicle"},
    "colon": {"zh": "结肠", "en": "Colon"},
    "common_carotid_artery_left": {"zh": "左颈总动脉", "en": "Left common carotid artery"},
    "common_carotid_artery_right": {"zh": "右颈总动脉", "en": "Right common carotid artery"},
    "costal_cartilages": {"zh": "肋软骨", "en": "Costal cartilages"},
    "cricoid_cartilage": {"zh": "环状软骨", "en": "Cricoid cartilage"},
    "crown": {"zh": "修复牙冠", "en": "Dental crown"},
    "digastric_left": {"zh": "左二腹肌", "en": "Left digastric muscle"},
    "digastric_right": {"zh": "右二腹肌", "en": "Right digastric muscle"},
    "duodenum": {"zh": "十二指肠", "en": "Duodenum"},
    "erector_spinae_left": {"zh": "左竖脊肌", "en": "Left erector spinae"},
    "erector_spinae_right": {"zh": "右竖脊肌", "en": "Right erector spinae"},
    "esophagus": {"zh": "食管", "en": "Esophagus"},
    "external_oblique_left": {"zh": "左腹外斜肌", "en": "Left external oblique"},
    "external_oblique_right": {"zh": "右腹外斜肌", "en": "Right external oblique"},
    "eye_left": {"zh": "左眼", "en": "Left eye"},
    "eye_lens_left": {"zh": "左眼晶状体", "en": "Left eye lens"},
    "eye_lens_right": {"zh": "右眼晶状体", "en": "Right eye lens"},
    "eye_right": {"zh": "右眼", "en": "Right eye"},
    "eyeball_left": {"zh": "左眼球", "en": "Left eyeball"},
    "eyeball_right": {"zh": "右眼球", "en": "Right eyeball"},
    "femur_left": {"zh": "左股骨", "en": "Left femur"},
    "femur_right": {"zh": "右股骨", "en": "Right femur"},
    "fourth_ventricle": {"zh": "第四脑室", "en": "Fourth ventricle"},
    "gallbladder": {"zh": "胆囊", "en": "Gallbladder"},
    "gluteus_maximus_left": {"zh": "左臀大肌", "en": "Left gluteus maximus"},
    "gluteus_maximus_right": {"zh": "右臀大肌", "en": "Right gluteus maximus"},
    "gluteus_medius_left": {"zh": "左臀中肌", "en": "Left gluteus medius"},
    "gluteus_medius_right": {"zh": "右臀中肌", "en": "Right gluteus medius"},
    "gluteus_minimus_left": {"zh": "左臀小肌", "en": "Left gluteus minimus"},
    "gluteus_minimus_right": {"zh": "右臀小肌", "en": "Right gluteus minimus"},
    "hard_palate": {"zh": "硬腭", "en": "Hard palate"},
    "head": {"zh": "头部", "en": "Head"},
    "heart": {"zh": "心脏整体", "en": "Whole heart"},
    "hip_implant": {"zh": "髋关节植入物", "en": "Hip implant"},
    "hip_left": {"zh": "左髋骨", "en": "Left hip bone"},
    "hip_right": {"zh": "右髋骨", "en": "Right hip bone"},
    "humerus_left": {"zh": "左肱骨", "en": "Left humerus"},
    "humerus_right": {"zh": "右肱骨", "en": "Right humerus"},
    "hyoid": {"zh": "舌骨", "en": "Hyoid bone"},
    "hypopharynx": {"zh": "下咽", "en": "Hypopharynx"},
    "iliac_artery_left": {"zh": "左髂动脉", "en": "Left iliac artery"},
    "iliac_artery_right": {"zh": "右髂动脉", "en": "Right iliac artery"},
    "iliac_vena_left": {"zh": "左髂静脉", "en": "Left iliac vein"},
    "iliac_vena_right": {"zh": "右髂静脉", "en": "Right iliac vein"},
    "iliopsoas_left": {"zh": "左髂腰肌", "en": "Left iliopsoas"},
    "iliopsoas_right": {"zh": "右髂腰肌", "en": "Right iliopsoas"},
    "implant": {"zh": "牙种植体", "en": "Dental implant"},
    "inferior_oblique_muscle_left": {"zh": "左眼下斜肌", "en": "Left inferior oblique eye muscle"},
    "inferior_oblique_muscle_right": {"zh": "右眼下斜肌", "en": "Right inferior oblique eye muscle"},
    "inferior_pharyngeal_constrictor": {"zh": "咽下缩肌", "en": "Inferior pharyngeal constrictor"},
    "inferior_rectus_muscle_left": {"zh": "左眼下直肌", "en": "Left inferior rectus eye muscle"},
    "inferior_rectus_muscle_right": {"zh": "右眼下直肌", "en": "Right inferior rectus eye muscle"},
    "inferior_vena_cava": {"zh": "下腔静脉", "en": "Inferior vena cava"},
    "internal_carotid_artery_left": {"zh": "左颈内动脉", "en": "Left internal carotid artery"},
    "internal_carotid_artery_right": {"zh": "右颈内动脉", "en": "Right internal carotid artery"},
    "internal_jugular_vein_left": {"zh": "左颈内静脉", "en": "Left internal jugular vein"},
    "internal_jugular_vein_right": {"zh": "右颈内静脉", "en": "Right internal jugular vein"},
    "internal_oblique_left": {"zh": "左腹内斜肌", "en": "Left internal oblique"},
    "internal_oblique_right": {"zh": "右腹内斜肌", "en": "Right internal oblique"},
    "intervertebral_discs": {"zh": "椎间盘", "en": "Intervertebral discs"},
    "intracerebral_hemorrhage": {"zh": "脑内出血", "en": "Intracerebral hemorrhage"},
    "kidney_cyst_left": {"zh": "左肾囊肿", "en": "Left kidney cyst"},
    "kidney_cyst_right": {"zh": "右肾囊肿", "en": "Right kidney cyst"},
    "kidney_left": {"zh": "左肾", "en": "Left kidney"},
    "kidney_right": {"zh": "右肾", "en": "Right kidney"},
    "larynx_air": {"zh": "喉腔", "en": "Laryngeal air space"},
    "lateral_pterygoid_left": {"zh": "左翼外肌", "en": "Left lateral pterygoid"},
    "lateral_pterygoid_right": {"zh": "右翼外肌", "en": "Right lateral pterygoid"},
    "lateral_rectus_muscle_left": {"zh": "左眼外直肌", "en": "Left lateral rectus eye muscle"},
    "lateral_rectus_muscle_right": {"zh": "右眼外直肌", "en": "Right lateral rectus eye muscle"},
    "latissimus_dorsi_left": {"zh": "左背阔肌", "en": "Left latissimus dorsi"},
    "latissimus_dorsi_right": {"zh": "右背阔肌", "en": "Right latissimus dorsi"},
    "left_inferior_alveolar_canal": {"zh": "左下牙槽管", "en": "Left inferior alveolar canal"},
    "left_mandibular_incisive_canal_fdi103": {"zh": "左下颌切牙管", "en": "Left mandibular incisive canal"},
    "left_maxillary_sinus": {"zh": "左上颌窦", "en": "Left maxillary sinus"},
    "levator_palpebrae_superioris_left": {"zh": "左上睑提肌", "en": "Left levator palpebrae superioris"},
    "levator_palpebrae_superioris_right": {"zh": "右上睑提肌", "en": "Right levator palpebrae superioris"},
    "levator_scapulae_left": {"zh": "左肩胛提肌", "en": "Left levator scapulae"},
    "levator_scapulae_right": {"zh": "右肩胛提肌", "en": "Right levator scapulae"},
    "lingual_canal": {"zh": "舌侧管", "en": "Lingual canal"},
    "liver": {"zh": "肝脏", "en": "Liver"},
    "liver_lesions": {"zh": "肝病灶", "en": "Liver lesions"},
    "liver_segment_1": {"zh": "肝第 1 段", "en": "Liver segment 1"},
    "liver_segment_2": {"zh": "肝第 2 段", "en": "Liver segment 2"},
    "liver_segment_3": {"zh": "肝第 3 段", "en": "Liver segment 3"},
    "liver_segment_4": {"zh": "肝第 4 段", "en": "Liver segment 4"},
    "liver_segment_5": {"zh": "肝第 5 段", "en": "Liver segment 5"},
    "liver_segment_6": {"zh": "肝第 6 段", "en": "Liver segment 6"},
    "liver_segment_7": {"zh": "肝第 7 段", "en": "Liver segment 7"},
    "liver_segment_8": {"zh": "肝第 8 段", "en": "Liver segment 8"},
    "liver_tumor": {"zh": "肝肿瘤", "en": "Liver tumor"},
    "liver_vessels": {"zh": "肝血管", "en": "Liver vessels"},
    "lower_jawbone": {"zh": "下颌骨", "en": "Mandible"},
    "lower_left_canine_fdi33": {"zh": "左下尖牙（33）", "en": "Lower left canine (33)"},
    "lower_left_canine_pulp_fdi133": {"zh": "左下尖牙牙髓（33）", "en": "Lower left canine pulp (33)"},
    "lower_left_central_incisor_fdi31": {"zh": "左下中切牙（31）", "en": "Lower left central incisor (31)"},
    "lower_left_central_incisor_pulp_fdi131": {"zh": "左下中切牙牙髓（31）", "en": "Lower left central incisor pulp (31)"},
    "lower_left_first_molar_fdi36": {"zh": "左下第一磨牙（36）", "en": "Lower left first molar (36)"},
    "lower_left_first_molar_pulp_fdi136": {"zh": "左下第一磨牙牙髓（36）", "en": "Lower left first molar pulp (36)"},
    "lower_left_first_premolar_fdi34": {"zh": "左下第一前磨牙（34）", "en": "Lower left first premolar (34)"},
    "lower_left_first_premolar_pulp_fdi134": {"zh": "左下第一前磨牙牙髓（34）", "en": "Lower left first premolar pulp (34)"},
    "lower_left_lateral_incisor_fdi32": {"zh": "左下侧切牙（32）", "en": "Lower left lateral incisor (32)"},
    "lower_left_lateral_incisor_pulp_fdi132": {"zh": "左下侧切牙牙髓（32）", "en": "Lower left lateral incisor pulp (32)"},
    "lower_left_second_molar_fdi37": {"zh": "左下第二磨牙（37）", "en": "Lower left second molar (37)"},
    "lower_left_second_molar_pulp_fdi137": {"zh": "左下第二磨牙牙髓（37）", "en": "Lower left second molar pulp (37)"},
    "lower_left_second_premolar_fdi35": {"zh": "左下第二前磨牙（35）", "en": "Lower left second premolar (35)"},
    "lower_left_second_premolar_pulp_fdi135": {"zh": "左下第二前磨牙牙髓（35）", "en": "Lower left second premolar pulp (35)"},
    "lower_left_third_molar_fdi38": {"zh": "左下第三磨牙（38）", "en": "Lower left third molar (38)"},
    "lower_left_third_molar_pulp_fdi138": {"zh": "左下第三磨牙牙髓（38）", "en": "Lower left third molar pulp (38)"},
    "lower_right_canine_fdi43": {"zh": "右下尖牙（43）", "en": "Lower right canine (43)"},
    "lower_right_canine_pulp_fdi143": {"zh": "右下尖牙牙髓（43）", "en": "Lower right canine pulp (43)"},
    "lower_right_central_incisor_fdi41": {"zh": "右下中切牙（41）", "en": "Lower right central incisor (41)"},
    "lower_right_central_incisor_pulp_fdi141": {"zh": "右下中切牙牙髓（41）", "en": "Lower right central incisor pulp (41)"},
    "lower_right_first_molar_fdi46": {"zh": "右下第一磨牙（46）", "en": "Lower right first molar (46)"},
    "lower_right_first_molar_pulp_fdi146": {"zh": "右下第一磨牙牙髓（46）", "en": "Lower right first molar pulp (46)"},
    "lower_right_first_premolar_fdi44": {"zh": "右下第一前磨牙（44）", "en": "Lower right first premolar (44)"},
    "lower_right_first_premolar_pulp_fdi144": {"zh": "右下第一前磨牙牙髓（44）", "en": "Lower right first premolar pulp (44)"},
    "lower_right_lateral_incisor_fdi42": {"zh": "右下侧切牙（42）", "en": "Lower right lateral incisor (42)"},
    "lower_right_lateral_incisor_pulp_fdi142": {"zh": "右下侧切牙牙髓（42）", "en": "Lower right lateral incisor pulp (42)"},
    "lower_right_second_molar_fdi47": {"zh": "右下第二磨牙（47）", "en": "Lower right second molar (47)"},
    "lower_right_second_molar_pulp_fdi147": {"zh": "右下第二磨牙牙髓（47）", "en": "Lower right second molar pulp (47)"},
    "lower_right_second_premolar_fdi45": {"zh": "右下第二前磨牙（45）", "en": "Lower right second premolar (45)"},
    "lower_right_second_premolar_pulp_fdi145": {"zh": "右下第二前磨牙牙髓（45）", "en": "Lower right second premolar pulp (45)"},
    "lower_right_third_molar_fdi48": {"zh": "右下第三磨牙（48）", "en": "Lower right third molar (48)"},
    "lower_right_third_molar_pulp_fdi148": {"zh": "右下第三磨牙牙髓（48）", "en": "Lower right third molar pulp (48)"},
    "lung": {"zh": "肺", "en": "Lung"},
    "lung_airways": {"zh": "肺气道", "en": "Lung airways"},
    "lung_airways_wall": {"zh": "肺气道壁", "en": "Lung airway walls"},
    "lung_arteries": {"zh": "肺动脉", "en": "Pulmonary arteries"},
    "lung_left": {"zh": "左肺", "en": "Left lung"},
    "lung_lower_lobe_left": {"zh": "左肺下叶", "en": "Left lower lung lobe"},
    "lung_lower_lobe_right": {"zh": "右肺下叶", "en": "Right lower lung lobe"},
    "lung_middle_lobe_right": {"zh": "右肺中叶", "en": "Right middle lung lobe"},
    "lung_nodules": {"zh": "肺结节", "en": "Lung nodules"},
    "lung_pleural": {"zh": "肺与胸膜区域", "en": "Lung and pleural region"},
    "lung_right": {"zh": "右肺", "en": "Right lung"},
    "lung_trachea_bronchia": {"zh": "气管与支气管", "en": "Trachea and bronchi"},
    "lung_upper_lobe_left": {"zh": "左肺上叶", "en": "Left upper lung lobe"},
    "lung_upper_lobe_right": {"zh": "右肺上叶", "en": "Right upper lung lobe"},
    "lung_veins": {"zh": "肺静脉", "en": "Pulmonary veins"},
    "lung_vessels": {"zh": "肺血管", "en": "Lung vessels"},
    "lungs": {"zh": "双肺", "en": "Lungs"},
    "mandible": {"zh": "下颌骨", "en": "Mandible"},
    "masseter_left": {"zh": "左咬肌", "en": "Left masseter"},
    "masseter_right": {"zh": "右咬肌", "en": "Right masseter"},
    "medial_pterygoid_left": {"zh": "左翼内肌", "en": "Left medial pterygoid"},
    "medial_pterygoid_right": {"zh": "右翼内肌", "en": "Right medial pterygoid"},
    "medial_rectus_muscle_left": {"zh": "左眼内直肌", "en": "Left medial rectus eye muscle"},
    "medial_rectus_muscle_right": {"zh": "右眼内直肌", "en": "Right medial rectus eye muscle"},
    "mediastinum": {"zh": "纵隔", "en": "Mediastinum"},
    "middle_pharyngeal_constrictor": {"zh": "咽中缩肌", "en": "Middle pharyngeal constrictor"},
    "middle_scalene_left": {"zh": "左中斜角肌", "en": "Left middle scalene"},
    "middle_scalene_right": {"zh": "右中斜角肌", "en": "Right middle scalene"},
    "nasal_cavity_left": {"zh": "左鼻腔", "en": "Left nasal cavity"},
    "nasal_cavity_right": {"zh": "右鼻腔", "en": "Right nasal cavity"},
    "nasopharynx": {"zh": "鼻咽", "en": "Nasopharynx"},
    "optic_nerve_left": {"zh": "左视神经", "en": "Left optic nerve"},
    "optic_nerve_right": {"zh": "右视神经", "en": "Right optic nerve"},
    "oropharynx": {"zh": "口咽", "en": "Oropharynx"},
    "pancreas": {"zh": "胰腺", "en": "Pancreas"},
    "parotid_gland_left": {"zh": "左腮腺", "en": "Left parotid gland"},
    "parotid_gland_right": {"zh": "右腮腺", "en": "Right parotid gland"},
    "pectoralis_major_left": {"zh": "左胸大肌", "en": "Left pectoralis major"},
    "pectoralis_major_right": {"zh": "右胸大肌", "en": "Right pectoralis major"},
    "pericardial_effusion": {"zh": "心包积液", "en": "Pericardial effusion"},
    "pericardium": {"zh": "心包", "en": "Pericardium"},
    "pharynx": {"zh": "咽", "en": "Pharynx"},
    "platysma_left": {"zh": "左颈阔肌", "en": "Left platysma"},
    "platysma_right": {"zh": "右颈阔肌", "en": "Right platysma"},
    "pleural_effusion": {"zh": "胸腔积液", "en": "Pleural effusion"},
    "portal_vein_and_splenic_vein": {"zh": "门静脉与脾静脉", "en": "Portal and splenic veins"},
    "posterior_scalene_left": {"zh": "左后斜角肌", "en": "Left posterior scalene"},
    "posterior_scalene_right": {"zh": "右后斜角肌", "en": "Right posterior scalene"},
    "prevertebral_left": {"zh": "左椎前肌", "en": "Left prevertebral muscles"},
    "prevertebral_right": {"zh": "右椎前肌", "en": "Right prevertebral muscles"},
    "prostate": {"zh": "前列腺", "en": "Prostate"},
    "psoas_major_left": {"zh": "左腰大肌", "en": "Left psoas major"},
    "psoas_major_right": {"zh": "右腰大肌", "en": "Right psoas major"},
    "pulmonary_vein": {"zh": "肺静脉", "en": "Pulmonary vein"},
    "quadratus_lumborum_left": {"zh": "左腰方肌", "en": "Left quadratus lumborum"},
    "quadratus_lumborum_right": {"zh": "右腰方肌", "en": "Right quadratus lumborum"},
    "rectus_abdominis_left": {"zh": "左腹直肌", "en": "Left rectus abdominis"},
    "rectus_abdominis_right": {"zh": "右腹直肌", "en": "Right rectus abdominis"},
    "rib_left_1": {"zh": "左第 1 肋", "en": "Left rib 1"},
    "rib_left_10": {"zh": "左第 10 肋", "en": "Left rib 10"},
    "rib_left_11": {"zh": "左第 11 肋", "en": "Left rib 11"},
    "rib_left_12": {"zh": "左第 12 肋", "en": "Left rib 12"},
    "rib_left_2": {"zh": "左第 2 肋", "en": "Left rib 2"},
    "rib_left_3": {"zh": "左第 3 肋", "en": "Left rib 3"},
    "rib_left_4": {"zh": "左第 4 肋", "en": "Left rib 4"},
    "rib_left_5": {"zh": "左第 5 肋", "en": "Left rib 5"},
    "rib_left_6": {"zh": "左第 6 肋", "en": "Left rib 6"},
    "rib_left_7": {"zh": "左第 7 肋", "en": "Left rib 7"},
    "rib_left_8": {"zh": "左第 8 肋", "en": "Left rib 8"},
    "rib_left_9": {"zh": "左第 9 肋", "en": "Left rib 9"},
    "rib_right_1": {"zh": "右第 1 肋", "en": "Right rib 1"},
    "rib_right_10": {"zh": "右第 10 肋", "en": "Right rib 10"},
    "rib_right_11": {"zh": "右第 11 肋", "en": "Right rib 11"},
    "rib_right_12": {"zh": "右第 12 肋", "en": "Right rib 12"},
    "rib_right_2": {"zh": "右第 2 肋", "en": "Right rib 2"},
    "rib_right_3": {"zh": "右第 3 肋", "en": "Right rib 3"},
    "rib_right_4": {"zh": "右第 4 肋", "en": "Right rib 4"},
    "rib_right_5": {"zh": "右第 5 肋", "en": "Right rib 5"},
    "rib_right_6": {"zh": "右第 6 肋", "en": "Right rib 6"},
    "rib_right_7": {"zh": "右第 7 肋", "en": "Right rib 7"},
    "rib_right_8": {"zh": "右第 8 肋", "en": "Right rib 8"},
    "rib_right_9": {"zh": "右第 9 肋", "en": "Right rib 9"},
    "right_inferior_alveolar_canal": {"zh": "右下牙槽管", "en": "Right inferior alveolar canal"},
    "right_mandibular_incisive_canal_fdi104": {"zh": "右下颌切牙管", "en": "Right mandibular incisive canal"},
    "right_maxillary_sinus": {"zh": "右上颌窦", "en": "Right maxillary sinus"},
    "sacrum": {"zh": "骶骨", "en": "Sacrum"},
    "scapula_left": {"zh": "左肩胛骨", "en": "Left scapula"},
    "scapula_right": {"zh": "右肩胛骨", "en": "Right scapula"},
    "serratus_anterior_left": {"zh": "左前锯肌", "en": "Left serratus anterior"},
    "serratus_anterior_right": {"zh": "右前锯肌", "en": "Right serratus anterior"},
    "sinus_frontal": {"zh": "额窦", "en": "Frontal sinus"},
    "sinus_maxillary": {"zh": "上颌窦", "en": "Maxillary sinus"},
    "skull": {"zh": "颅骨", "en": "Skull"},
    "small_bowel": {"zh": "小肠", "en": "Small bowel"},
    "soft_palate": {"zh": "软腭", "en": "Soft palate"},
    "spinal_cord": {"zh": "脊髓", "en": "Spinal cord"},
    "spleen": {"zh": "脾脏", "en": "Spleen"},
    "sterno_thyroid_left": {"zh": "左胸骨甲状肌", "en": "Left sternothyroid"},
    "sterno_thyroid_right": {"zh": "右胸骨甲状肌", "en": "Right sternothyroid"},
    "sternocleidomastoid_left": {"zh": "左胸锁乳突肌", "en": "Left sternocleidomastoid"},
    "sternocleidomastoid_right": {"zh": "右胸锁乳突肌", "en": "Right sternocleidomastoid"},
    "sternum": {"zh": "胸骨", "en": "Sternum"},
    "stomach": {"zh": "胃", "en": "Stomach"},
    "styloid_process_left": {"zh": "左茎突", "en": "Left styloid process"},
    "styloid_process_right": {"zh": "右茎突", "en": "Right styloid process"},
    "subclavian_artery_left": {"zh": "左锁骨下动脉", "en": "Left subclavian artery"},
    "subclavian_artery_right": {"zh": "右锁骨下动脉", "en": "Right subclavian artery"},
    "submandibular_gland_left": {"zh": "左下颌下腺", "en": "Left submandibular gland"},
    "submandibular_gland_right": {"zh": "右下颌下腺", "en": "Right submandibular gland"},
    "superior_oblique_muscle_left": {"zh": "左眼上斜肌", "en": "Left superior oblique eye muscle"},
    "superior_oblique_muscle_right": {"zh": "右眼上斜肌", "en": "Right superior oblique eye muscle"},
    "superior_pharyngeal_constrictor": {"zh": "咽上缩肌", "en": "Superior pharyngeal constrictor"},
    "superior_rectus_muscle_left": {"zh": "左眼上直肌", "en": "Left superior rectus eye muscle"},
    "superior_rectus_muscle_right": {"zh": "右眼上直肌", "en": "Right superior rectus eye muscle"},
    "superior_vena_cava": {"zh": "上腔静脉", "en": "Superior vena cava"},
    "teeth_lower": {"zh": "下颌牙列", "en": "Lower teeth"},
    "teeth_upper": {"zh": "上颌牙列", "en": "Upper teeth"},
    "temporalis_left": {"zh": "左颞肌", "en": "Left temporalis"},
    "temporalis_right": {"zh": "右颞肌", "en": "Right temporalis"},
    "third_ventricle": {"zh": "第三脑室", "en": "Third ventricle"},
    "thoracic_cavity": {"zh": "胸腔", "en": "Thoracic cavity"},
    "thyrohyoid_left": {"zh": "左甲状舌骨肌", "en": "Left thyrohyoid"},
    "thyrohyoid_right": {"zh": "右甲状舌骨肌", "en": "Right thyrohyoid"},
    "thyroid_cartilage": {"zh": "甲状软骨", "en": "Thyroid cartilage"},
    "thyroid_gland": {"zh": "甲状腺", "en": "Thyroid gland"},
    "tongue": {"zh": "舌", "en": "Tongue"},
    "trachea": {"zh": "气管", "en": "Trachea"},
    "transversospinalis_left": {"zh": "左横突棘肌", "en": "Left transversospinalis"},
    "transversospinalis_right": {"zh": "右横突棘肌", "en": "Right transversospinalis"},
    "trapezius_left": {"zh": "左斜方肌", "en": "Left trapezius"},
    "trapezius_right": {"zh": "右斜方肌", "en": "Right trapezius"},
    "upper_jawbone": {"zh": "上颌骨", "en": "Maxilla"},
    "upper_left_canine_fdi23": {"zh": "左上尖牙（23）", "en": "Upper left canine (23)"},
    "upper_left_canine_pulp_fdi123": {"zh": "左上尖牙牙髓（23）", "en": "Upper left canine pulp (23)"},
    "upper_left_central_incisor_fdi21": {"zh": "左上中切牙（21）", "en": "Upper left central incisor (21)"},
    "upper_left_central_incisor_pulp_fdi121": {"zh": "左上中切牙牙髓（21）", "en": "Upper left central incisor pulp (21)"},
    "upper_left_first_molar_fdi26": {"zh": "左上第一磨牙（26）", "en": "Upper left first molar (26)"},
    "upper_left_first_molar_pulp_fdi126": {"zh": "左上第一磨牙牙髓（26）", "en": "Upper left first molar pulp (26)"},
    "upper_left_first_premolar_fdi24": {"zh": "左上第一前磨牙（24）", "en": "Upper left first premolar (24)"},
    "upper_left_first_premolar_pulp_fdi124": {"zh": "左上第一前磨牙牙髓（24）", "en": "Upper left first premolar pulp (24)"},
    "upper_left_lateral_incisor_fdi22": {"zh": "左上侧切牙（22）", "en": "Upper left lateral incisor (22)"},
    "upper_left_lateral_incisor_pulp_fdi122": {"zh": "左上侧切牙牙髓（22）", "en": "Upper left lateral incisor pulp (22)"},
    "upper_left_second_molar_fdi27": {"zh": "左上第二磨牙（27）", "en": "Upper left second molar (27)"},
    "upper_left_second_molar_pulp_fdi127": {"zh": "左上第二磨牙牙髓（27）", "en": "Upper left second molar pulp (27)"},
    "upper_left_second_premolar_fdi25": {"zh": "左上第二前磨牙（25）", "en": "Upper left second premolar (25)"},
    "upper_left_second_premolar_pulp_fdi125": {"zh": "左上第二前磨牙牙髓（25）", "en": "Upper left second premolar pulp (25)"},
    "upper_left_third_molar_fdi28": {"zh": "左上第三磨牙（28）", "en": "Upper left third molar (28)"},
    "upper_left_third_molar_pulp_fdi128": {"zh": "左上第三磨牙牙髓（28）", "en": "Upper left third molar pulp (28)"},
    "upper_right_canine_fdi13": {"zh": "右上尖牙（13）", "en": "Upper right canine (13)"},
    "upper_right_canine_pulp_fdi113": {"zh": "右上尖牙牙髓（13）", "en": "Upper right canine pulp (13)"},
    "upper_right_central_incisor_fdi11": {"zh": "右上中切牙（11）", "en": "Upper right central incisor (11)"},
    "upper_right_central_incisor_pulp_fdi111": {"zh": "右上中切牙牙髓（11）", "en": "Upper right central incisor pulp (11)"},
    "upper_right_first_molar_fdi16": {"zh": "右上第一磨牙（16）", "en": "Upper right first molar (16)"},
    "upper_right_first_molar_pulp_fdi116": {"zh": "右上第一磨牙牙髓（16）", "en": "Upper right first molar pulp (16)"},
    "upper_right_first_premolar_fdi14": {"zh": "右上第一前磨牙（14）", "en": "Upper right first premolar (14)"},
    "upper_right_first_premolar_pulp_fdi114": {"zh": "右上第一前磨牙牙髓（14）", "en": "Upper right first premolar pulp (14)"},
    "upper_right_lateral_incisor_fdi12": {"zh": "右上侧切牙（12）", "en": "Upper right lateral incisor (12)"},
    "upper_right_lateral_incisor_pulp_fdi112": {"zh": "右上侧切牙牙髓（12）", "en": "Upper right lateral incisor pulp (12)"},
    "upper_right_second_molar_fdi17": {"zh": "右上第二磨牙（17）", "en": "Upper right second molar (17)"},
    "upper_right_second_molar_pulp_fdi117": {"zh": "右上第二磨牙牙髓（17）", "en": "Upper right second molar pulp (17)"},
    "upper_right_second_premolar_fdi15": {"zh": "右上第二前磨牙（15）", "en": "Upper right second premolar (15)"},
    "upper_right_second_premolar_pulp_fdi115": {"zh": "右上第二前磨牙牙髓（15）", "en": "Upper right second premolar pulp (15)"},
    "upper_right_third_molar_fdi18": {"zh": "右上第三磨牙（18）", "en": "Upper right third molar (18)"},
    "upper_right_third_molar_pulp_fdi118": {"zh": "右上第三磨牙牙髓（18）", "en": "Upper right third molar pulp (18)"},
    "urinary_bladder": {"zh": "膀胱", "en": "Urinary bladder"},
    "ventricle_body_left": {"zh": "左侧脑室体部", "en": "Left lateral ventricle body"},
    "ventricle_body_right": {"zh": "右侧脑室体部", "en": "Right lateral ventricle body"},
    "ventricle_frontal_horn_left": {"zh": "左侧脑室前角", "en": "Left lateral ventricle frontal horn"},
    "ventricle_frontal_horn_right": {"zh": "右侧脑室前角", "en": "Right lateral ventricle frontal horn"},
    "ventricle_occipital_horn_left": {"zh": "左侧脑室后角", "en": "Left lateral ventricle occipital horn"},
    "ventricle_occipital_horn_right": {"zh": "右侧脑室后角", "en": "Right lateral ventricle occipital horn"},
    "ventricle_temporal_horn_left": {"zh": "左侧脑室下角", "en": "Left lateral ventricle temporal horn"},
    "ventricle_temporal_horn_right": {"zh": "右侧脑室下角", "en": "Right lateral ventricle temporal horn"},
    "ventricle_trigone_left": {"zh": "左侧脑室三角区", "en": "Left lateral ventricle trigone"},
    "ventricle_trigone_right": {"zh": "右侧脑室三角区", "en": "Right lateral ventricle trigone"},
    "vertebrae": {"zh": "椎骨", "en": "Vertebrae"},
    "vertebrae_C1": {"zh": "第 1 颈椎", "en": "Cervical vertebra C1"},
    "vertebrae_C2": {"zh": "第 2 颈椎", "en": "Cervical vertebra C2"},
    "vertebrae_C3": {"zh": "第 3 颈椎", "en": "Cervical vertebra C3"},
    "vertebrae_C4": {"zh": "第 4 颈椎", "en": "Cervical vertebra C4"},
    "vertebrae_C5": {"zh": "第 5 颈椎", "en": "Cervical vertebra C5"},
    "vertebrae_C6": {"zh": "第 6 颈椎", "en": "Cervical vertebra C6"},
    "vertebrae_C7": {"zh": "第 7 颈椎", "en": "Cervical vertebra C7"},
    "vertebrae_L1": {"zh": "第 1 腰椎", "en": "Lumbar vertebra L1"},
    "vertebrae_L2": {"zh": "第 2 腰椎", "en": "Lumbar vertebra L2"},
    "vertebrae_L3": {"zh": "第 3 腰椎", "en": "Lumbar vertebra L3"},
    "vertebrae_L4": {"zh": "第 4 腰椎", "en": "Lumbar vertebra L4"},
    "vertebrae_L5": {"zh": "第 5 腰椎", "en": "Lumbar vertebra L5"},
    "vertebrae_L6": {"zh": "第 6 腰椎", "en": "Lumbar vertebra L6"},
    "vertebrae_S1": {"zh": "第 1 骶椎", "en": "Sacral vertebra S1"},
    "vertebrae_T1": {"zh": "第 1 胸椎", "en": "Thoracic vertebra T1"},
    "vertebrae_T10": {"zh": "第 10 胸椎", "en": "Thoracic vertebra T10"},
    "vertebrae_T11": {"zh": "第 11 胸椎", "en": "Thoracic vertebra T11"},
    "vertebrae_T12": {"zh": "第 12 胸椎", "en": "Thoracic vertebra T12"},
    "vertebrae_T2": {"zh": "第 2 胸椎", "en": "Thoracic vertebra T2"},
    "vertebrae_T3": {"zh": "第 3 胸椎", "en": "Thoracic vertebra T3"},
    "vertebrae_T4": {"zh": "第 4 胸椎", "en": "Thoracic vertebra T4"},
    "vertebrae_T5": {"zh": "第 5 胸椎", "en": "Thoracic vertebra T5"},
    "vertebrae_T6": {"zh": "第 6 胸椎", "en": "Thoracic vertebra T6"},
    "vertebrae_T7": {"zh": "第 7 胸椎", "en": "Thoracic vertebra T7"},
    "vertebrae_T8": {"zh": "第 8 胸椎", "en": "Thoracic vertebra T8"},
    "vertebrae_T9": {"zh": "第 9 胸椎", "en": "Thoracic vertebra T9"},
    "vertebrae_body": {"zh": "椎体", "en": "Vertebral bodies"},
    "zygomatic_arch_left": {"zh": "左颧弓", "en": "Left zygomatic arch"},
    "zygomatic_arch_right": {"zh": "右颧弓", "en": "Right zygomatic arch"},
  }));

  window.MedSegLabels = Object.freeze({
    has: (name) => names.has(name),
    displayName(name, id, locale) {
      const translated = names.get(name);
      if (translated) return locale === "en" ? translated.en : translated.zh;
      // Unknown/user-defined labels retain their identity instead of guessing anatomy.
      if (locale === "en" && typeof name === "string" && /^[a-z][a-z0-9_]*$/.test(name)) {
        const label = name.replaceAll("_", " ");
        return label.charAt(0).toUpperCase() + label.slice(1);
      }
      return name || String(id);
    },
  });
})();
